// Steps shown in the header (excludes welcome and confirmation)
export const FLOW_STEPS = ['area', 'location', 'device', 'classification', 'review'];

export const TRANSLATIONS = {
  en: {
    appName: 'RyderTag',
    selectLanguage: 'Select your language',
    selectWarehouse: 'Which warehouse are you located in?',
    startReport: 'Start Report',
    whereIssue: 'Where is the issue?',
    specifyLocation: 'Specify the exact location.',
    stationNumber: 'Station Number',
    workstationNumber: 'Workstation Number',
    dockDoorNumber: 'Dock Door Number',
    whatEquipment: 'What equipment has the issue?',
    whoFillingOut: 'Who is this report for?',
    whoSubtitle: 'This device requires user identification',
    yourName: 'Your Name',
    namePlaceholder: 'e.g. Maria Rodriguez',
    issueClassification: 'What best describes the problem?',
    reviewSubmit: 'Review & Submit',
    editReport: 'Edit Report',
    submitTicket: 'Submit Ticket',
    ticketSubmitted: 'Your issue has been submitted successfully.',
    thankYou: 'Thank you!',
    reportAnother: 'Report Another Issue',
    returnHome: 'Return Home',
    next: 'Next',
    back: 'Back',
    home: 'Home',
    continue: 'Continue',
    selectArea: 'Tap the area where the issue is located',
    selectDevice: 'Tap the equipment with the issue',
    locationConfirmed: 'Location Confirmed',
    area: 'Area',
    location: 'Location',
    device: 'Device',
    reporter: 'Reporter',
    issue: 'Issue',
    comments: 'Comments',
    typeHere: 'Type here...',
    mostCommon: 'Most Common',
    fillAtLeastOne: 'Please fill in at least one field',
    warehouses: {
      w1: 'Warehouse 1',
      w2: 'Warehouse 2',
      w3: 'Warehouse 3',
      w4: 'Warehouse 4',
    },
    areas: {
      inbound: 'Inbound',
      outbound: 'Outbound',
      mainFrontOffice: 'Main Front Office',
      dockDoor: 'Dock Door',
      packingArea: 'Packing Area',
      shippingArea: 'Shipping Area',
      receivingArea: 'Receiving Area',
      stagingArea: 'Staging Area',
      mobileWorkstation: 'Mobile Workstation',
      other: 'Other',
    },
    devices: {
      Printer: 'Printer',
      Monitor: 'Monitor',
      Scanner: 'Scanner',
      Scale: 'Scale',
      Laptop: 'Laptop',
      Desktop: 'Desktop',
      Keyboard: 'Keyboard',
      Mouse: 'Mouse',
      'Power Outlet': 'Power Outlet',
      'Network Connection': 'Network',
      YubiKey: 'YubiKey',
      'Label Printer': 'Label Printer',
      'Handheld Device': 'Handheld',
      Cables: 'Cables',
      Other: 'Other',
    },
  },
  es: {
    appName: 'RyderTag',
    selectLanguage: 'Seleccione su idioma',
    selectWarehouse: '¿En qué almacén se encuentra?',
    startReport: 'Iniciar Reporte',
    whereIssue: '¿Dónde está el problema?',
    specifyLocation: 'Especifique la ubicación exacta.',
    stationNumber: 'Número de Estación',
    workstationNumber: 'Número de Estación de Trabajo',
    dockDoorNumber: 'Número de Puerta de Muelle',
    whatEquipment: '¿Qué equipo tiene el problema?',
    whoFillingOut: '¿Para quién es este reporte?',
    whoSubtitle: 'Este dispositivo requiere identificación del usuario',
    yourName: 'Su Nombre',
    namePlaceholder: 'ej. Maria Rodriguez',
    issueClassification: '¿Qué describe mejor el problema?',
    reviewSubmit: 'Revisar y Enviar',
    editReport: 'Editar Reporte',
    submitTicket: 'Enviar Ticket',
    ticketSubmitted: 'Su problema fue enviado exitosamente.',
    thankYou: '¡Gracias!',
    reportAnother: 'Reportar Otro Problema',
    returnHome: 'Volver al Inicio',
    next: 'Siguiente',
    back: 'Atrás',
    home: 'Inicio',
    continue: 'Continuar',
    selectArea: 'Toque el área donde está el problema',
    selectDevice: 'Toque el equipo con el problema',
    locationConfirmed: 'Ubicación Confirmada',
    area: 'Área',
    location: 'Ubicación',
    device: 'Equipo',
    reporter: 'Reportante',
    issue: 'Problema',
    comments: 'Comentarios',
    typeHere: 'Escriba aquí...',
    mostCommon: 'Más Común',
    fillAtLeastOne: 'Por favor complete al menos un campo',
    warehouses: {
      w1: 'Almacén 1',
      w2: 'Almacén 2',
      w3: 'Almacén 3',
      w4: 'Almacén 4',
    },
    areas: {
      inbound: 'Entrada',
      outbound: 'Salida',
      mainFrontOffice: 'Oficina Principal',
      dockDoor: 'Puerta de Muelle',
      packingArea: 'Área de Empaque',
      shippingArea: 'Área de Envío',
      receivingArea: 'Área de Recepción',
      stagingArea: 'Área de Preparación',
      mobileWorkstation: 'Estación de Trabajo Móvil',
      other: 'Otro',
    },
    devices: {
      Printer: 'Impresora',
      Monitor: 'Monitor',
      Scanner: 'Escáner',
      Scale: 'Báscula',
      Laptop: 'Laptop',
      Desktop: 'Escritorio',
      Keyboard: 'Teclado',
      Mouse: 'Ratón',
      'Power Outlet': 'Toma de Corriente',
      'Network Connection': 'Red',
      YubiKey: 'YubiKey',
      'Label Printer': 'Impresora de Etiquetas',
      'Handheld Device': 'Dispositivo de Mano',
      Cables: 'Cables',
      Other: 'Otro',
    },
  },
  ht: {
    appName: 'RyderTag',
    selectLanguage: 'Chwazi lang ou',
    selectWarehouse: 'Nan ki depo w ye?',
    startReport: 'Kòmanse Rapò',
    whereIssue: 'Ki kote pwoblèm nan ye?',
    specifyLocation: 'Presize kote egzak la.',
    stationNumber: 'Nimewo Estasyon',
    workstationNumber: 'Nimewo Estasyon Travay',
    dockDoorNumber: 'Nimewo Pòt Dok',
    whatEquipment: 'Ki ekipman ki gen pwoblèm?',
    whoFillingOut: 'Pou kiyès rapò sa a ye?',
    whoSubtitle: 'Aparèy sa a mande idantifikasyon itilizatè',
    yourName: 'Non Ou',
    namePlaceholder: 'egz. Maria Rodriguez',
    issueClassification: 'Ki sa ki pi byen dekri pwoblèm nan?',
    reviewSubmit: 'Revize ak Soumèt',
    editReport: 'Modifye Rapò',
    submitTicket: 'Soumèt Tikè',
    ticketSubmitted: 'Pwoblèm ou an te soumèt avèk siksè.',
    thankYou: 'Mèsi!',
    reportAnother: 'Rapòte yon Lòt Pwoblèm',
    returnHome: 'Retounen Lakay',
    next: 'Swivan',
    back: 'Retounen',
    home: 'Akèy',
    continue: 'Kontinye',
    selectArea: 'Tape zòn kote pwoblèm nan ye',
    selectDevice: 'Tape ekipman ki gen pwoblèm nan',
    locationConfirmed: 'Kote Konfime',
    area: 'Zòn',
    location: 'Kote',
    device: 'Ekipman',
    reporter: 'Moun k ap Rapòte',
    issue: 'Pwoblèm',
    comments: 'Kòmantè',
    typeHere: 'Ekri isit...',
    mostCommon: 'Pi Souvan',
    fillAtLeastOne: 'Tanpri ranpli omwen yon chan',
    warehouses: {
      w1: 'Depo 1',
      w2: 'Depo 2',
      w3: 'Depo 3',
      w4: 'Depo 4',
    },
    areas: {
      inbound: 'Antre',
      outbound: 'Sòti',
      mainFrontOffice: 'Biwo Prensipal',
      dockDoor: 'Pòt Dok',
      packingArea: 'Zòn Anbalaj',
      shippingArea: 'Zòn Ekspedisyon',
      receivingArea: 'Zòn Resepsyon',
      stagingArea: 'Zòn Preparasyon',
      mobileWorkstation: 'Estasyon Travay Mobil',
      other: 'Lòt',
    },
    devices: {
      Printer: 'Enprimant',
      Monitor: 'Ekran',
      Scanner: 'Skenè',
      Scale: 'Balans',
      Laptop: 'Laptop',
      Desktop: 'Òdinatè Tab',
      Keyboard: 'Klavye',
      Mouse: 'Sourit',
      'Power Outlet': 'Pri Kouran',
      'Network Connection': 'Rezo',
      YubiKey: 'YubiKey',
      'Label Printer': 'Enprimant Etikèt',
      'Handheld Device': 'Aparèy Pòtatif',
      Cables: 'Kab',
      Other: 'Lòt',
    },
  },
  pt: {
    appName: 'RyderTag',
    selectLanguage: 'Selecione seu idioma',
    selectWarehouse: 'Em qual armazém você está localizado?',
    startReport: 'Iniciar Relatório',
    whereIssue: 'Onde está o problema?',
    specifyLocation: 'Especifique o local exato.',
    stationNumber: 'Número da Estação',
    workstationNumber: 'Número da Estação de Trabalho',
    dockDoorNumber: 'Número da Porta de Doca',
    whatEquipment: 'Qual equipamento tem o problema?',
    whoFillingOut: 'Para quem é este relatório?',
    whoSubtitle: 'Este dispositivo requer identificação do usuário',
    yourName: 'Seu Nome',
    namePlaceholder: 'ex. Maria Rodriguez',
    issueClassification: 'O que melhor descreve o problema?',
    reviewSubmit: 'Revisar e Enviar',
    editReport: 'Editar Relatório',
    submitTicket: 'Enviar Ticket',
    ticketSubmitted: 'Seu problema foi enviado com sucesso.',
    thankYou: 'Obrigado!',
    reportAnother: 'Relatar Outro Problema',
    returnHome: 'Retornar ao Início',
    next: 'Próximo',
    back: 'Voltar',
    home: 'Início',
    continue: 'Continuar',
    selectArea: 'Toque na área onde o problema está',
    selectDevice: 'Toque no equipamento com o problema',
    locationConfirmed: 'Local Confirmado',
    area: 'Área',
    location: 'Local',
    device: 'Equipamento',
    reporter: 'Responsável',
    issue: 'Problema',
    comments: 'Comentários',
    typeHere: 'Digite aqui...',
    mostCommon: 'Mais Comum',
    fillAtLeastOne: 'Por favor preencha pelo menos um campo',
    warehouses: {
      w1: 'Armazém 1',
      w2: 'Armazém 2',
      w3: 'Armazém 3',
      w4: 'Armazém 4',
    },
    areas: {
      inbound: 'Entrada',
      outbound: 'Saída',
      mainFrontOffice: 'Escritório Principal',
      dockDoor: 'Porta de Doca',
      packingArea: 'Área de Embalagem',
      shippingArea: 'Área de Envio',
      receivingArea: 'Área de Recebimento',
      stagingArea: 'Área de Preparação',
      mobileWorkstation: 'Estação de Trabalho Móvel',
      other: 'Outro',
    },
    devices: {
      Printer: 'Impressora',
      Monitor: 'Monitor',
      Scanner: 'Scanner',
      Scale: 'Balança',
      Laptop: 'Laptop',
      Desktop: 'Computador de Mesa',
      Keyboard: 'Teclado',
      Mouse: 'Mouse',
      'Power Outlet': 'Tomada',
      'Network Connection': 'Rede',
      YubiKey: 'YubiKey',
      'Label Printer': 'Impressora de Etiquetas',
      'Handheld Device': 'Dispositivo Portátil',
      Cables: 'Cabos',
      Other: 'Outro',
    },
  },
};

export const ISSUE_CATEGORIES = {
  Printer: [
    { en: 'Not Powering On', es: 'No Enciende', ht: 'Pa Ka Alimante', pt: 'Não Liga' },
    { en: 'Printer Offline', es: 'Impresora Fuera de Línea', ht: 'Enprimant Òflìn', pt: 'Impressora Offline' },
    { en: 'Label Not Printing', es: 'Etiqueta No Imprime', ht: 'Etikèt Pa Enprime', pt: 'Etiqueta Não Imprime' },
    { en: 'Poor Print Quality', es: 'Mala Calidad de Impresión', ht: 'Move Kalite Enpresyon', pt: 'Má Qualidade de Impressão' },
    { en: 'Paper Jam', es: 'Atasco de Papel', ht: 'Blokaj Papye', pt: 'Atolamento de Papel' },
    { en: 'Wrong Labels Printing', es: 'Etiquetas Incorrectas', ht: 'Move Etikèt', pt: 'Etiquetas Erradas' },
    { en: 'Connection Issue', es: 'Problema de Conexión', ht: 'Pwoblèm Koneksyon', pt: 'Problema de Conexão' },
    { en: 'Error Message', es: 'Mensaje de Error', ht: 'Mesaj Erè', pt: 'Mensagem de Erro' },
    { en: 'Slow Printing', es: 'Impresión Lenta', ht: 'Enpresyon Lan', pt: 'Impressão Lenta' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  'Label Printer': [
    { en: 'Not Powering On', es: 'No Enciende', ht: 'Pa Ka Alimante', pt: 'Não Liga' },
    { en: 'Label Not Printing', es: 'Etiqueta No Imprime', ht: 'Etikèt Pa Enprime', pt: 'Etiqueta Não Imprime' },
    { en: 'Poor Print Quality', es: 'Mala Calidad', ht: 'Move Kalite', pt: 'Má Qualidade' },
    { en: 'Paper Jam', es: 'Atasco', ht: 'Blokaj', pt: 'Atolamento' },
    { en: 'Wrong Labels Printing', es: 'Etiquetas Incorrectas', ht: 'Move Etikèt', pt: 'Etiquetas Erradas' },
    { en: 'Connection Issue', es: 'Problema de Conexión', ht: 'Pwoblèm Koneksyon', pt: 'Problema de Conexão' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  Monitor: [
    { en: "Won't Turn On", es: 'No Enciende', ht: 'Pa Ka Alimante', pt: 'Não Liga' },
    { en: 'Blank Screen / No Signal', es: 'Pantalla Negra / Sin Señal', ht: 'Ekran Nwa / Pa Gen Siyal', pt: 'Tela Preta / Sem Sinal' },
    { en: 'Flickering Screen', es: 'Pantalla Parpadeante', ht: 'Ekran k ap Klignote', pt: 'Tela Piscando' },
    { en: 'Dim Screen', es: 'Pantalla Tenue', ht: 'Ekran Fèb', pt: 'Tela Fraca' },
    { en: 'Dead Pixels', es: 'Píxeles Muertos', ht: 'Piksèl Mouri', pt: 'Pixels Mortos' },
    { en: 'Blurry Display', es: 'Imagen Borrosa', ht: 'Afichaj Flou', pt: 'Imagem Borrada' },
    { en: 'Touch Screen Not Working', es: 'Pantalla Táctil No Funciona', ht: 'Ekran Taktil Pa Travay', pt: 'Tela Touch Não Funciona' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  Scanner: [
    { en: "Won't Power On / Battery", es: 'No Enciende / Batería', ht: 'Pa Ka Alimante / Batri', pt: 'Não Liga / Bateria' },
    { en: "Won't Read Barcodes", es: 'No Lee Códigos de Barras', ht: 'Pa Ka Li Kòd-ba', pt: 'Não Lê Códigos de Barras' },
    { en: 'Connection Issues (WiFi)', es: 'Problemas de Conexión (WiFi)', ht: 'Pwoblèm Koneksyon (WiFi)', pt: 'Problemas de Conexão (WiFi)' },
    { en: 'Scanner Disconnects Frequently', es: 'Escáner se Desconecta', ht: 'Skenè Dekonekte Souvan', pt: 'Scanner Desconecta Frequentemente' },
    { en: 'Trigger Not Working', es: 'Gatillo No Funciona', ht: 'Gachèt Pa Travay', pt: 'Gatilho Não Funciona' },
    { en: 'Screen / Keypad Issues', es: 'Problemas de Pantalla / Teclado', ht: 'Pwoblèm Ekran / Klavye', pt: 'Problemas de Tela / Teclado' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'False Read', es: 'Lectura Falsa', ht: 'Fo Lekti', pt: 'Leitura Falsa' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  'Handheld Device': [
    { en: "Won't Power On / Battery", es: 'No Enciende / Batería', ht: 'Pa Ka Alimante / Batri', pt: 'Não Liga / Bateria' },
    { en: "Won't Read Barcodes", es: 'No Lee Códigos de Barras', ht: 'Pa Ka Li Kòd-ba', pt: 'Não Lê Códigos de Barras' },
    { en: 'Connection Issues (WiFi)', es: 'Problemas de Conexión (WiFi)', ht: 'Pwoblèm Koneksyon (WiFi)', pt: 'Problemas de Conexão (WiFi)' },
    { en: 'Scanner Disconnects Frequently', es: 'Escáner se Desconecta', ht: 'Skenè Dekonekte Souvan', pt: 'Scanner Desconecta Frequentemente' },
    { en: 'Trigger Not Working', es: 'Gatillo No Funciona', ht: 'Gachèt Pa Travay', pt: 'Gatilho Não Funciona' },
    { en: 'Screen / Keypad Issues', es: 'Problemas de Pantalla / Teclado', ht: 'Pwoblèm Ekran / Klavye', pt: 'Problemas de Tela / Teclado' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'False Read', es: 'Lectura Falsa', ht: 'Fo Lekti', pt: 'Leitura Falsa' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  Scale: [
    { en: "Won't Power On", es: 'No Enciende', ht: 'Pa Ka Alimante', pt: 'Não Liga' },
    { en: 'Incorrect Readings', es: 'Lecturas Incorrectas', ht: 'Move Lekti', pt: 'Leituras Incorretas' },
    { en: 'Weight Fluctuation', es: 'Fluctuación de Peso', ht: 'Fliktiyasyon Pwa', pt: 'Flutuação de Peso' },
    { en: "Scale Won't Zero", es: 'Balanza No Se Pone a Cero', ht: 'Balans Pa Ka Zewo', pt: 'Balança Não Zera' },
    { en: 'Display Not Working', es: 'Pantalla No Funciona', ht: 'Afichaj Pa Travay', pt: 'Display Não Funciona' },
    { en: 'Communication Issues w/ Shipping Software', es: 'Problemas con Software de Envío', ht: 'Pwoblèm ak Lojisyèl Ekspedisyon', pt: 'Problemas com Software de Envio' },
    { en: 'Overload Errors', es: 'Errores de Sobrecarga', ht: 'Erè Sipachaj', pt: 'Erros de Sobrecarga' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  Keyboard: [
    { en: 'Keys Not Working', es: 'Teclas No Funcionan', ht: 'Kle Pa Travay', pt: 'Teclas Não Funcionam' },
    { en: 'Keyboard Disconnects', es: 'Teclado se Desconecta', ht: 'Klavye Dekonekte', pt: 'Teclado Desconecta' },
    { en: 'Liquid Damage', es: 'Daño por Líquido', ht: 'Domaj Likid', pt: 'Dano por Líquido' },
    { en: 'Cable Issue', es: 'Problema con Cable', ht: 'Pwoblèm Kab', pt: 'Problema com Cabo' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  Mouse: [
    { en: 'Not Responding', es: 'No Responde', ht: 'Pa Reponn', pt: 'Não Responde' },
    { en: 'Not Moving Properly', es: 'No Se Mueve Bien', ht: 'Pa Deplase Kòrèkteman', pt: 'Não Move Corretamente' },
    { en: 'Scroll Wheel Issue', es: 'Problema con la Rueda', ht: 'Pwoblèm Wou Defilman', pt: 'Problema com a Roda de Rolagem' },
    { en: 'Mouse Disconnects', es: 'Ratón se Desconecta', ht: 'Sourit Dekonekte', pt: 'Mouse Desconecta' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  Cables: [
    { en: 'Loose Connection', es: 'Conexión Suelta', ht: 'Koneksyon Lach', pt: 'Conexão Solta' },
    { en: 'Damaged Cable', es: 'Cable Dañado', ht: 'Kab Domaje', pt: 'Cabo Danificado' },
    { en: 'Ethernet Cable', es: 'Cable Ethernet', ht: 'Kab Ethernet', pt: 'Cabo Ethernet' },
    { en: 'HDMI Cable', es: 'Cable HDMI', ht: 'Kab HDMI', pt: 'Cabo HDMI' },
    { en: 'USB Cable', es: 'Cable USB', ht: 'Kab USB', pt: 'Cabo USB' },
    { en: 'Power Cable', es: 'Cable de Poder', ht: 'Kab Kouran', pt: 'Cabo de Energia' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  Other: [
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  'Power Outlet': [
    { en: 'No Power', es: 'Sin Energía', ht: 'Pa Gen Kouran', pt: 'Sem Energia' },
    { en: 'Intermittent Power Loss', es: 'Pérdida Intermitente de Energía', ht: 'Pèt Kouran Entèmitan', pt: 'Perda Intermitente de Energia' },
    { en: 'Tripped Circuit Breaker', es: 'Disyuntor Disparado', ht: 'Disfòntè Klanche', pt: 'Disjuntor Desarmado' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'Low Voltage', es: 'Bajo Voltaje', ht: 'Ba Vòltaj', pt: 'Baixa Tensão' },
    { en: 'Charging Station Issue', es: 'Problema con Estación de Carga', ht: 'Pwoblèm Estasyon Chaj', pt: 'Problema com Estação de Carregamento' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  'Network Connection': [
    { en: 'No Internet / Network', es: 'Sin Internet / Red', ht: 'Pa Gen Entènèt / Rezo', pt: 'Sem Internet / Rede' },
    { en: 'Slow Connection', es: 'Conexión Lenta', ht: 'Koneksyon Lan', pt: 'Conexão Lenta' },
    { en: 'WiFi Dropping', es: 'WiFi se Cae', ht: 'WiFi Tonbe', pt: 'WiFi Caindo' },
    { en: 'Cannot Connect to Network', es: 'No Puede Conectarse', ht: 'Pa Ka Konekte', pt: 'Não Consegue Conectar' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  YubiKey: [
    { en: 'YubiKey Not Detected', es: 'YubiKey No Detectado', ht: 'YubiKey Pa Detekte', pt: 'YubiKey Não Detectado' },
    { en: 'Unable to Login', es: 'No Puede Iniciar Sesión', ht: 'Pa Ka Konekte', pt: 'Não Consegue Fazer Login' },
    { en: 'Token Not Recognized', es: 'Token No Reconocido', ht: 'Token Pa Rekonèt', pt: 'Token Não Reconhecido' },
    { en: 'Lost YubiKey', es: 'YubiKey Perdido', ht: 'YubiKey Pèdi', pt: 'YubiKey Perdido' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'Credentials / Login Problem', es: 'Problema de Credenciales', ht: 'Pwoblèm Akreditasyon', pt: 'Problema de Credenciais' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  Laptop: [
    { en: "Won't Power On", es: 'No Enciende', ht: 'Pa Ka Alimante', pt: 'Não Liga' },
    { en: 'Not Charging', es: 'No Carga', ht: 'Pa Ka Chaje', pt: 'Não Carrega' },
    { en: 'WiFi / Network Issue', es: 'Problema WiFi / Red', ht: 'Pwoblèm WiFi / Rezo', pt: 'Problema WiFi / Rede' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'No Display', es: 'Sin Imagen', ht: 'Pa Gen Afichaj', pt: 'Sem Imagem' },
    { en: 'Freezing / Crashing', es: 'Se Congela / Falla', ht: 'Bloke / Kraze', pt: 'Congela / Trava' },
    { en: 'Port Not Working', es: 'Puerto No Funciona', ht: 'Pò Pa Travay', pt: 'Porta Não Funciona' },
    { en: 'Login Problem', es: 'Problema de Inicio de Sesión', ht: 'Pwoblèm Koneksyon', pt: 'Problema de Login' },
    { en: 'Application Error', es: 'Error de Aplicación', ht: 'Erè Aplikasyon', pt: 'Erro de Aplicação' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
  Desktop: [
    { en: "Won't Power On", es: 'No Enciende', ht: 'Pa Ka Alimante', pt: 'Não Liga' },
    { en: 'WiFi / Network Issue', es: 'Problema WiFi / Red', ht: 'Pwoblèm WiFi / Rezo', pt: 'Problema WiFi / Rede' },
    { en: 'Physical Damage', es: 'Daño Físico', ht: 'Domaj Fizik', pt: 'Dano Físico' },
    { en: 'No Display', es: 'Sin Imagen', ht: 'Pa Gen Afichaj', pt: 'Sem Imagem' },
    { en: 'Freezing / Crashing', es: 'Se Congela / Falla', ht: 'Bloke / Kraze', pt: 'Congela / Trava' },
    { en: 'Port Not Working', es: 'Puerto No Funciona', ht: 'Pò Pa Travay', pt: 'Porta Não Funciona' },
    { en: 'Login Problem', es: 'Problema de Inicio de Sesión', ht: 'Pwoblèm Koneksyon', pt: 'Problema de Login' },
    { en: 'Application Error', es: 'Error de Aplicación', ht: 'Erè Aplikasyon', pt: 'Erro de Aplicação' },
    { en: 'Other', es: 'Otro', ht: 'Lòt', pt: 'Outro' },
  ],
};